// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include <tgbot/net/LibCoroHttpClient.hpp>
#include <httplib.h>

namespace TgBot {
    namespace net {
        LibCoroHttpClient::LibCoroHttpClient(std::string host)
            : host_(std::move(host)), client_(host_) {
        client_.set_connection_timeout(10);
    }

    coro::task<std::string> LibCoroHttpClient::makeRequest(const HttpVerb verb, const std::string& target, const std::string& body, const std::string& contentType) {
        httplib::Result res;
        if (verb == HttpVerb::POST) {
            res = client_.Post(target, body, contentType);
        } else {
            res = client_.Get(target);
        }

        if (res && res->status == 200) {
            co_return res->body;
        } else if (res) {
            throw std::runtime_error("Telegram API Error: HTTP " + std::to_string(res->status));
        } else {
            auto err = res.error();
            throw std::runtime_error("HTTP Request failed: " + httplib::to_string(err));
        }
    }

    }
}
