// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include <tgbot/net/TelegramException.hpp>

namespace TgBot {
    TgException::TgException(const std::string& description, ErrorCode errorCode)
        : std::runtime_error(description), errorCode(errorCode) {}
}
