// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Use this method to get the token of a managed bot. Returns the token as String on success.
     *
     * @param user_id User identifier of the managed bot whose token will be returned
     */
    struct GetManagedBotTokenRequest {
        typedef std::shared_ptr<GetManagedBotTokenRequest> Ptr;
        // User identifier of the managed bot whose token will be returned
        std::int64_t user_id = 0;
    };
    void to_json(json& j, const GetManagedBotTokenRequest& value);
    void from_json(const json& j, GetManagedBotTokenRequest& value);
}
