// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Use this method to revoke the current token of a managed bot and generate a new one. Returns the new token as String on success.
     *
     * @param user_id User identifier of the managed bot whose token will be replaced
     */
    struct ReplaceManagedBotTokenRequest {
        typedef std::shared_ptr<ReplaceManagedBotTokenRequest> Ptr;
        // User identifier of the managed bot whose token will be replaced
        std::int64_t user_id = 0;
    };
    void to_json(json& j, const ReplaceManagedBotTokenRequest& value);
    void from_json(const json& j, ReplaceManagedBotTokenRequest& value);
}
