// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <tgbot/types/KeyboardButton.hpp>

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Stores a keyboard button that can be used by a user within a Mini App. Returns a PreparedKeyboardButton object.
     *
     * @param user_id Unique identifier of the target user that can use the button
     * @param button A JSON-serialized object describing the button to be saved. The button must be of the type request_users, request_chat, or request_managed_bot
     */
    struct SavePreparedKeyboardButtonRequest {
        typedef std::shared_ptr<SavePreparedKeyboardButtonRequest> Ptr;
        // Unique identifier of the target user that can use the button
        std::int64_t user_id = 0;

        // A JSON-serialized object describing the button to be saved. The button must be of the type request_users, request_chat, or request_managed_bot
        KeyboardButton::Ptr button = nullptr;
    };
    void to_json(json& j, const SavePreparedKeyboardButtonRequest& value);
    void from_json(const json& j, SavePreparedKeyboardButtonRequest& value);
}
