// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include <tgbot/types/InputProfilePhoto.hpp>

namespace TgBot {
    void to_json(json& j, const InputProfilePhoto& value) { }
    void from_json(const json& j, InputProfilePhoto& value) { }
}
