// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include <tgbot/types/KeyboardButtonRequestManagedBot.hpp>
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const KeyboardButtonRequestManagedBot& value) {
        j = json{};
        j["request_id"] = value.request_id;
    if (!value.suggested_name.empty()) { 
                    j["suggested_name"] = value.suggested_name; 
            }
    if (!value.suggested_username.empty()) { 
                    j["suggested_username"] = value.suggested_username; 
            }
    }

    void from_json(const json& j, KeyboardButtonRequestManagedBot& value) {
        if (j.contains("request_id")) {
            j.at("request_id").get_to(value.request_id);
        }
        if (j.contains("suggested_name")) {
            j.at("suggested_name").get_to(value.suggested_name);
        }
        if (j.contains("suggested_username")) {
            j.at("suggested_username").get_to(value.suggested_username);
        }
    }
}
