// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include <tgbot/types/ManagedBotCreated.hpp>
#include <tgbot/types/User.hpp>
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const ManagedBotCreated& value) {
        j = json{};
        j["bot"] = value.bot;
    }

    void from_json(const json& j, ManagedBotCreated& value) {
        if (j.contains("bot")) {
            j.at("bot").get_to(value.bot);
        }
    }
}
