// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include <tgbot/types/PollOption.hpp>
#include <tgbot/types/User.hpp>
#include <tgbot/types/Chat.hpp>
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const PollOption& value) {
        j = json{};
        j["persistent_id"] = value.persistent_id;
        j["text"] = value.text;
        j["voter_count"] = value.voter_count;
    if (!value.text_entities.empty()) { 
                    j["text_entities"] = value.text_entities; 
            }
    if (value.added_by_user) { 
                    j["added_by_user"] = value.added_by_user; 
            }
    if (value.added_by_chat) { 
                    j["added_by_chat"] = value.added_by_chat; 
            }
    if (value.addition_date != 0) { 
                    j["addition_date"] = value.addition_date; 
            }
    }

    void from_json(const json& j, PollOption& value) {
        if (j.contains("persistent_id")) {
            j.at("persistent_id").get_to(value.persistent_id);
        }
        if (j.contains("text")) {
            j.at("text").get_to(value.text);
        }
        if (j.contains("voter_count")) {
            j.at("voter_count").get_to(value.voter_count);
        }
        if (j.contains("text_entities")) {
            j.at("text_entities").get_to(value.text_entities);
        }
        if (j.contains("added_by_user")) {
            j.at("added_by_user").get_to(value.added_by_user);
        }
        if (j.contains("added_by_chat")) {
            j.at("added_by_chat").get_to(value.added_by_chat);
        }
        if (j.contains("addition_date")) {
            j.at("addition_date").get_to(value.addition_date);
        }
    }
}
