// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include <tgbot/types/Poll.hpp>
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const Poll& value) {
        j = json{};
        j["id"] = value.id;
        j["question"] = value.question;
        j["options"] = value.options;
        j["total_voter_count"] = value.total_voter_count;
        j["is_closed"] = value.is_closed;
        j["is_anonymous"] = value.is_anonymous;
        j["type"] = value.type_;
        j["allows_multiple_answers"] = value.allows_multiple_answers;
        j["allows_revoting"] = value.allows_revoting;
    if (!value.question_entities.empty()) { 
                    j["question_entities"] = value.question_entities; 
            }
    if (!value.correct_option_ids.empty()) { 
                    j["correct_option_ids"] = value.correct_option_ids; 
            }
    if (!value.explanation.empty()) { 
                    j["explanation"] = value.explanation; 
            }
    if (!value.explanation_entities.empty()) { 
                    j["explanation_entities"] = value.explanation_entities; 
            }
    if (value.open_period != 0) { 
                    j["open_period"] = value.open_period; 
            }
    if (value.close_date != 0) { 
                    j["close_date"] = value.close_date; 
            }
    if (!value.description.empty()) { 
                    j["description"] = value.description; 
            }
    if (!value.description_entities.empty()) { 
                    j["description_entities"] = value.description_entities; 
            }
    }

    void from_json(const json& j, Poll& value) {
        if (j.contains("id")) {
            j.at("id").get_to(value.id);
        }
        if (j.contains("question")) {
            j.at("question").get_to(value.question);
        }
        if (j.contains("options")) {
            j.at("options").get_to(value.options);
        }
        if (j.contains("total_voter_count")) {
            j.at("total_voter_count").get_to(value.total_voter_count);
        }
        if (j.contains("is_closed")) {
            j.at("is_closed").get_to(value.is_closed);
        }
        if (j.contains("is_anonymous")) {
            j.at("is_anonymous").get_to(value.is_anonymous);
        }
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
        if (j.contains("allows_multiple_answers")) {
            j.at("allows_multiple_answers").get_to(value.allows_multiple_answers);
        }
        if (j.contains("allows_revoting")) {
            j.at("allows_revoting").get_to(value.allows_revoting);
        }
        if (j.contains("question_entities")) {
            j.at("question_entities").get_to(value.question_entities);
        }
        if (j.contains("correct_option_ids")) {
            j.at("correct_option_ids").get_to(value.correct_option_ids);
        }
        if (j.contains("explanation")) {
            j.at("explanation").get_to(value.explanation);
        }
        if (j.contains("explanation_entities")) {
            j.at("explanation_entities").get_to(value.explanation_entities);
        }
        if (j.contains("open_period")) {
            j.at("open_period").get_to(value.open_period);
        }
        if (j.contains("close_date")) {
            j.at("close_date").get_to(value.close_date);
        }
        if (j.contains("description")) {
            j.at("description").get_to(value.description);
        }
        if (j.contains("description_entities")) {
            j.at("description_entities").get_to(value.description_entities);
        }
    }
}
