// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include <tgbot/types/PollOptionDeleted.hpp>
#include <tgbot/types/MaybeInaccessibleMessage.hpp>
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const PollOptionDeleted& value) {
        j = json{};
        j["option_persistent_id"] = value.option_persistent_id;
        j["option_text"] = value.option_text;
    if (value.poll_message) { 
                    j["poll_message"] = value.poll_message; 
            }
    if (!value.option_text_entities.empty()) { 
                    j["option_text_entities"] = value.option_text_entities; 
            }
    }

    void from_json(const json& j, PollOptionDeleted& value) {
        if (j.contains("option_persistent_id")) {
            j.at("option_persistent_id").get_to(value.option_persistent_id);
        }
        if (j.contains("option_text")) {
            j.at("option_text").get_to(value.option_text);
        }
        if (j.contains("poll_message")) {
            j.at("poll_message").get_to(value.poll_message);
        }
        if (j.contains("option_text_entities")) {
            j.at("option_text_entities").get_to(value.option_text_entities);
        }
    }
}
