// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include <tgbot/types/PreparedKeyboardButton.hpp>
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const PreparedKeyboardButton& value) {
        j = json{};
        j["id"] = value.id;
    }

    void from_json(const json& j, PreparedKeyboardButton& value) {
        if (j.contains("id")) {
            j.at("id").get_to(value.id);
        }
    }
}
