// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include <tgbot/types/StoryArea.hpp>
#include <tgbot/types/StoryAreaPosition.hpp>
#include <tgbot/types/StoryAreaType.hpp>
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const StoryArea& value) {
        j = json{};
        j["position"] = value.position;
        j["type"] = value.type_;
    }

    void from_json(const json& j, StoryArea& value) {
        if (j.contains("position")) {
            j.at("position").get_to(value.position);
        }
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
    }
}
