// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <tgbot/EventBroadcaster.hpp>
#include <tgbot/types/Update.hpp>
#include <tgbot/tools/StringTools.hpp>
#include <algorithm>
#include <cstddef>
#include <string>
#include <coro/task.hpp>

namespace TgBot {

    class EventHandler {
    public:
        explicit EventHandler(const EventBroadcaster& broadcaster) : broadcaster_(broadcaster) {
        }

        coro::task<void> handleUpdate(const Update::Ptr& update) const;

    private:
        const EventBroadcaster& broadcaster_;

        coro::task<void> handleMessage(const Message::Ptr& message) const;
    };
}
