// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include <tgbot/Bot.hpp>
#include <tgbot/net/LibCoroHttpClient.hpp>
#include <tgbot/EventBroadcaster.hpp>
#include <memory>
#include <string>

namespace TgBot {
    Bot::Bot(std::string token, HttpClient& httpClient, const std::string& url)
        : token_(std::move(token))
        , api_(token_, httpClient, url)
        , eventBroadcaster_(std::make_unique<EventBroadcaster>())
        , eventHandler_(getEvents()) {
    }

    HttpClient& Bot::_getDefaultHttpClient() {
       static net::LibCoroHttpClient instance;
       return instance;
    }
}
