// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <tgbot/types/TelegramModel.hpp>

namespace TgBot {

    using json = nlohmann::json;

    /**
     * This object defines the parameters for the creation of a managed bot. Information about the created bot will be shared with the bot using the update managed_bot and a Message with the field managed_bot_created.
     *
     * @param request_id Signed 32-bit identifier of the request. Must be unique within the message
     * @param suggested_name Optional. Suggested name for the bot
     * @param suggested_username Optional. Suggested username for the bot
     */
    struct KeyboardButtonRequestManagedBot : public TelegramModel {
        typedef std::shared_ptr<KeyboardButtonRequestManagedBot> Ptr;
        typedef std::weak_ptr<KeyboardButtonRequestManagedBot> WeakPtr;

        virtual ~KeyboardButtonRequestManagedBot() = default;
        // Signed 32-bit identifier of the request. Must be unique within the message
        std::int64_t request_id = 0;

        // Optional. Suggested name for the bot
        std::string suggested_name = "";

        // Optional. Suggested username for the bot
        std::string suggested_username = "";
    };
    void to_json(json& j, const KeyboardButtonRequestManagedBot& value);
    void from_json(const json& j, KeyboardButtonRequestManagedBot& value);
}
