// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <tgbot/types/TelegramModel.hpp>
#include <tgbot/types/User.hpp>

namespace TgBot {

    using json = nlohmann::json;

    /**
     * This object contains information about the bot that was created to be managed by the current bot.
     *
     * @param bot Information about the bot. The bot's token can be fetched using the method getManagedBotToken.
     */
    struct ManagedBotCreated : public TelegramModel {
        typedef std::shared_ptr<ManagedBotCreated> Ptr;
        typedef std::weak_ptr<ManagedBotCreated> WeakPtr;

        virtual ~ManagedBotCreated() = default;
        // Information about the bot. The bot's token can be fetched using the method getManagedBotToken.
        User::Ptr bot = nullptr;
    };
    void to_json(json& j, const ManagedBotCreated& value);
    void from_json(const json& j, ManagedBotCreated& value);
}
