// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <tgbot/types/TelegramModel.hpp>
#include <tgbot/types/User.hpp>

namespace TgBot {

    using json = nlohmann::json;

    /**
     * This object contains information about the creation or token update of a bot that is managed by the current bot.
     *
     * @param user User that created the bot
     * @param bot Information about the bot. Token of the bot can be fetched using the method getManagedBotToken.
     */
    struct ManagedBotUpdated : public TelegramModel {
        typedef std::shared_ptr<ManagedBotUpdated> Ptr;
        typedef std::weak_ptr<ManagedBotUpdated> WeakPtr;

        virtual ~ManagedBotUpdated() = default;
        // User that created the bot
        User::Ptr user = nullptr;

        // Information about the bot. Token of the bot can be fetched using the method getManagedBotToken.
        User::Ptr bot = nullptr;
    };
    void to_json(json& j, const ManagedBotUpdated& value);
    void from_json(const json& j, ManagedBotUpdated& value);
}
