// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <tgbot/types/TelegramModel.hpp>
#include <tgbot/types/MessageEntity.hpp>
#include <tgbot/types/MaybeInaccessibleMessage.hpp>

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Describes a service message about an option added to a poll.
     *
     * @param option_persistent_id Unique identifier of the added option
     * @param option_text Option text
     * @param poll_message Optional. Message containing the poll to which the option was added, if known. Note that the Message object in this field will not contain the reply_to_message field even if it itself is a reply.
     * @param option_text_entities Optional. Special entities that appear in the option_text
     */
    struct PollOptionAdded : public TelegramModel {
        typedef std::shared_ptr<PollOptionAdded> Ptr;
        typedef std::weak_ptr<PollOptionAdded> WeakPtr;

        virtual ~PollOptionAdded() = default;
        // Unique identifier of the added option
        std::string option_persistent_id = "";

        // Option text
        std::string option_text = "";

        // Optional. Message containing the poll to which the option was added, if known. Note that the Message object in this field will not contain the reply_to_message field even if it itself is a reply.
        MaybeInaccessibleMessage::Ptr poll_message = nullptr;

        // Optional. Special entities that appear in the option_text
        std::vector<MessageEntity::Ptr> option_text_entities = std::vector<MessageEntity::Ptr>();
    };
    void to_json(json& j, const PollOptionAdded& value);
    void from_json(const json& j, PollOptionAdded& value);
}
