// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <tgbot/types/TelegramModel.hpp>
#include <tgbot/types/Chat.hpp>
#include <tgbot/types/User.hpp>

namespace TgBot {

    using json = nlohmann::json;

    /**
     * This object represents an answer of a user in a non-anonymous poll.
     *
     * @param poll_id Unique poll identifier
     * @param option_ids 0-based identifiers of chosen answer options. May be empty if the vote was retracted.
     * @param option_persistent_ids Persistent identifiers of the chosen answer options. May be empty if the vote was retracted.
     * @param voter_chat Optional. The chat that changed the answer to the poll, if the voter is anonymous
     * @param user Optional. The user that changed the answer to the poll, if the voter isn't anonymous
     */
    struct PollAnswer : public TelegramModel {
        typedef std::shared_ptr<PollAnswer> Ptr;
        typedef std::weak_ptr<PollAnswer> WeakPtr;

        virtual ~PollAnswer() = default;
        // Unique poll identifier
        std::string poll_id = "";

        // 0-based identifiers of chosen answer options. May be empty if the vote was retracted.
        std::vector<std::int64_t> option_ids = std::vector<std::int64_t>();

        // Persistent identifiers of the chosen answer options. May be empty if the vote was retracted.
        std::vector<std::string> option_persistent_ids = std::vector<std::string>();

        // Optional. The chat that changed the answer to the poll, if the voter is anonymous
        Chat::Ptr voter_chat = nullptr;

        // Optional. The user that changed the answer to the poll, if the voter isn't anonymous
        User::Ptr user = nullptr;
    };
    void to_json(json& j, const PollAnswer& value);
    void from_json(const json& j, PollAnswer& value);
}
