// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <tgbot/types/TelegramModel.hpp>
#include <tgbot/types/PollOption.hpp>
#include <tgbot/types/MessageEntity.hpp>

namespace TgBot {

    using json = nlohmann::json;

    /**
     * This object contains information about a poll.
     *
     * @param id Unique poll identifier
     * @param question Poll question, 1-300 characters
     * @param options List of poll options
     * @param total_voter_count Total number of users that voted in the poll
     * @param is_closed True, if the poll is closed
     * @param is_anonymous True, if the poll is anonymous
     * @param type Poll type, currently can be “regular” or “quiz”
     * @param allows_multiple_answers True, if the poll allows multiple answers
     * @param allows_revoting True, if the poll allows to change the chosen answer options
     * @param question_entities Optional. Special entities that appear in the question. Currently, only custom emoji entities are allowed in poll questions
     * @param correct_option_ids Optional. Array of 0-based identifiers of the correct answer options. Available only for polls in quiz mode which are closed or were sent (not forwarded) by the bot or to the private chat with the bot.
     * @param explanation Optional. Text that is shown when a user chooses an incorrect answer or taps on the lamp icon in a quiz-style poll, 0-200 characters
     * @param explanation_entities Optional. Special entities like usernames, URLs, bot commands, etc. that appear in the explanation
     * @param open_period Optional. Amount of time in seconds the poll will be active after creation
     * @param close_date Optional. Point in time (Unix timestamp) when the poll will be automatically closed
     * @param description Optional. Description of the poll; for polls inside the Message object only
     * @param description_entities Optional. Special entities like usernames, URLs, bot commands, etc. that appear in the description
     */
    struct Poll : public TelegramModel {
        typedef std::shared_ptr<Poll> Ptr;
        typedef std::weak_ptr<Poll> WeakPtr;

        virtual ~Poll() = default;
        // Unique poll identifier
        std::string id = "";

        // Poll question, 1-300 characters
        std::string question = "";

        // List of poll options
        std::vector<PollOption::Ptr> options = std::vector<PollOption::Ptr>();

        // Total number of users that voted in the poll
        std::int64_t total_voter_count = 0;

        // True, if the poll is closed
        bool is_closed = false;

        // True, if the poll is anonymous
        bool is_anonymous = false;

        // Poll type, currently can be “regular” or “quiz”
        std::string type_ = "";

        // True, if the poll allows multiple answers
        bool allows_multiple_answers = false;

        // True, if the poll allows to change the chosen answer options
        bool allows_revoting = false;

        // Optional. Special entities that appear in the question. Currently, only custom emoji entities are allowed in poll questions
        std::vector<MessageEntity::Ptr> question_entities = std::vector<MessageEntity::Ptr>();

        // Optional. Array of 0-based identifiers of the correct answer options. Available only for polls in quiz mode which are closed or were sent (not forwarded) by the bot or to the private chat with the bot.
        std::vector<std::int64_t> correct_option_ids = std::vector<std::int64_t>();

        // Optional. Text that is shown when a user chooses an incorrect answer or taps on the lamp icon in a quiz-style poll, 0-200 characters
        std::string explanation = "";

        // Optional. Special entities like usernames, URLs, bot commands, etc. that appear in the explanation
        std::vector<MessageEntity::Ptr> explanation_entities = std::vector<MessageEntity::Ptr>();

        // Optional. Amount of time in seconds the poll will be active after creation
        std::int64_t open_period = 0;

        // Optional. Point in time (Unix timestamp) when the poll will be automatically closed
        std::int64_t close_date = 0;

        // Optional. Description of the poll; for polls inside the Message object only
        std::string description = "";

        // Optional. Special entities like usernames, URLs, bot commands, etc. that appear in the description
        std::vector<MessageEntity::Ptr> description_entities = std::vector<MessageEntity::Ptr>();
    };
    void to_json(json& j, const Poll& value);
    void from_json(const json& j, Poll& value);
}
