// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include <tgbot/types/TelegramModel.hpp>

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Describes a keyboard button to be used by a user of a Mini App.
     *
     * @param id Unique identifier of the keyboard button
     */
    struct PreparedKeyboardButton : public TelegramModel {
        typedef std::shared_ptr<PreparedKeyboardButton> Ptr;
        typedef std::weak_ptr<PreparedKeyboardButton> WeakPtr;

        virtual ~PreparedKeyboardButton() = default;
        // Unique identifier of the keyboard button
        std::string id = "";
    };
    void to_json(json& j, const PreparedKeyboardButton& value);
    void from_json(const json& j, PreparedKeyboardButton& value);
}
