// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include <tgbot/requests/ReplaceManagedBotTokenRequest.hpp>

namespace TgBot {
    void to_json(json& j, const ReplaceManagedBotTokenRequest& value) {
        j = json{};
        j["user_id"] = value.user_id;
    }

    void from_json(const json& j, ReplaceManagedBotTokenRequest& value) {
        if (j.contains("user_id")) {
            j.at("user_id").get_to(value.user_id);
        }
    }
}
