// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include <tgbot/requests/SavePreparedKeyboardButtonRequest.hpp>

namespace TgBot {
    void to_json(json& j, const SavePreparedKeyboardButtonRequest& value) {
        j = json{};
        j["user_id"] = value.user_id;
        j["button"] = value.button;
    }

    void from_json(const json& j, SavePreparedKeyboardButtonRequest& value) {
        if (j.contains("user_id")) {
            j.at("user_id").get_to(value.user_id);
        }
        if (j.contains("button")) {
            j.at("button").get_to(value.button);
        }
    }
}
