// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <coro/task.hpp>
#include <string>

namespace TgBot {

    enum class HttpVerb {
        GET,
        POST
    };


    class HttpClient {
    public:
        virtual ~HttpClient() = default;

        [[nodiscard]]
        virtual coro::task<std::string> makeRequest(HttpVerb verb, const std::string& target, const std::string& body, const std::string& contentType) = 0;

        coro::task<std::string> makeRequest(const HttpVerb verb, const std::string& target, const std::string& body) {
            return makeRequest(verb, target, body, "application/json");
        }

        coro::task<std::string> makeRequest(const HttpVerb verb, const std::string& target) {
            return makeRequest(verb, target, "", "application/json");
        }
    };
}
