// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <tgbot/net/HttpClient.hpp>
#include <coro/coro.hpp>
#include <memory>
#include <string>
#include <httplib.h>

namespace TgBot {

    namespace net {

    class LibCoroHttpClient : public HttpClient {
        std::string host_;    
        httplib::SSLClient client_;

    public:
        explicit LibCoroHttpClient(std::string host = "api.telegram.org");

        [[nodiscard]]
        coro::task<std::string> makeRequest(HttpVerb verb, const std::string& target, const std::string& body, const std::string& contentType) override final;
    };

    }
}
