// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <stdexcept>
#include <string>
#include <cstddef>

namespace TgBot {

    class TgException : public std::runtime_error {
    public:
        enum class ErrorCode : size_t {
            Undefined = 0,
            BadRequest = 400, Unauthorized = 401, 
            Forbidden = 403, NotFound = 404, 
            Flood = 402, Internal = 500,
            HtmlResponse = 100, InvalidJson = 101
        };

        explicit TgException(const std::string& description, ErrorCode errorCode);

        const ErrorCode errorCode;
    };
}
